spring.application.name=SmartFood-ApiGateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


spring.cloud.gateway.server.webmvc.routes[0].id=user-service

spring.cloud.gateway.server.webmvc.routes[0].uri=lb://SmartFood-UserService

spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**,/users/**


spring.cloud.gateway.server.webmvc.routes[1].id=restaurant-service

spring.cloud.gateway.server.webmvc.routes[1].uri=lb://SmartFood-RestaurantService

spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/restaurants/**,/foods/**


spring.cloud.gateway.server.webmvc.routes[2].id=order-service

spring.cloud.gateway.server.webmvc.routes[2].uri=lb://SmartFood-OrderService

spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/orders/**,/cart/**



spring.cloud.gateway.server.webmvc.routes[3].id=payment-service

spring.cloud.gateway.server.webmvc.routes[3].uri=lb://SmartFood-PaymentService

spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/payments/**


spring.cloud.gateway.server.webmvc.routes[4].id=delivery-service

spring.cloud.gateway.server.webmvc.routes[4].uri=lb://SmartFood-DeliveryService

spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/deliveries/**



spring.cloud.gateway.server.webmvc.routes[5].id=notification-service

spring.cloud.gateway.server.webmvc.routes[5].uri=lb://SmartFood-NotificationService

spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/notifications/**



management.endpoints.web.exposure.include=*

management.endpoint.health.show-details=always



