spring.application.name=SmartFood-EurekaServer


server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

server.forward-headers-strategy=framework
management.endpoints.web.exposure.include=health,info
